export const storage = ['32 GB', '64 GB', '128 GB', '256 GB', '512 GB']

export const color = ['Siyah', 'Beyaz', 'Kırmızı', 'Mor', 'Mavi']

export const brands = [
   "Apple",
   "Samsung",
   "Xiaomi",
   "Huawei",
   "Alcatel",
   "Anka",
   "BB Mobile",
   "BlackBerry",
   "Casper",
   "Doogee",
   "Elephone",
   "General Mobile",
   "Hiking",
   "HONOR",
   "HTC",
   "Infinix",
   "LG",
   "Meizu",
   "Nokia",
   "Omix",
   "Oneplus",
   "Oppo",
   "Oukitel",
   "Philips",
   "POCO",
   "Realme",
   "Reeder",
   "TCL",
   "Tecno",
   "Trident",
   "Ulefone",
   "Vestel",
   "vivo",
   "ZTE"
]