export const devicesList = [
   { brand: 'Apple', model: 'Iphone 13 Pro', storage: '256GB', color: 'Siyah', price: '25.000₺' },
   { brand: 'Huawei', model: 'P20 Lite', storage: '128GB', color: 'Siyah', price: '5.000₺' },
   { brand: 'Samsung', model: 'Galaxy M12', storage: '128GB', color: 'Beyaz', price: '10.000₺' },
   { brand: 'Oppo', model: 'A74', storage: '128GB', color: 'Beyaz', price: '5.000₺' },
   { brand: 'Samsung', model: 'Galaxy S21', storage: '128GB', color: 'Beyaz', price: '5.000₺' },
   { brand: 'Apple', model: 'Iphone 11', storage: '256GB', color: 'Siyah', price: '15.000₺' },
   { brand: 'Huawei', model: 'Nova 9', storage: '128GB', color: 'Siyah', price: '5.000₺' },
   { brand: 'Apple', model: 'Iphone SE', storage: '512GB', color: 'Siyah', price: '15.000₺' },
   { brand: 'Samsung', model: 'Galaxy A23', storage: '128GB', color: 'Beyaz', price: '15.000₺' },
   { brand: 'Xiaomi', model: 'Redmi 9c', storage: '128GB', color: 'Siyah', price: '5.000₺' },
   { brand: 'Apple', model: 'Iphone 12', storage: '128GB', color: 'Beyaz', price: '20.000₺' },
   { brand: 'Apple', model: 'Iphone 11', storage: '256GB', color: 'Siyah', price: '15.000₺' },
   { brand: 'Samsung', model: 'Galaxy S20', storage: '256GB', color: 'Beyaz', price: '25.000₺' },
   { brand: 'Huawei', model: 'Nova 9', storage: '128GB', color: 'Siyah', price: '5.000₺' },
   { brand: 'Samsung', model: 'Galaxy S21', storage: '128GB', color: 'Beyaz', price: '5.000₺' },
   { brand: 'Samsung', model: 'Galaxy A23', storage: '128GB', color: 'Beyaz', price: '15.000₺' },
   { brand: 'Apple', model: 'Iphone SE', storage: '512GB', color: 'Siyah', price: '15.000₺' },
   { brand: 'Samsung', model: 'Galaxy M12', storage: '128GB', color: 'Beyaz', price: '10.000₺' },
   { brand: 'Huawei', model: 'P20 Lite', storage: '128GB', color: 'Siyah', price: '5.000₺' },
   { brand: 'Huawei', model: 'Nova 9', storage: '128GB', color: 'Siyah', price: '5.000₺' },
   { brand: 'Samsung', model: 'Galaxy S21', storage: '128GB', color: 'Beyaz', price: '5.000₺' },
   { brand: 'Huawei', model: 'Nova 9', storage: '128GB', color: 'Siyah', price: '5.000₺' },
   { brand: 'Samsung', model: 'Galaxy S21', storage: '128GB', color: 'Beyaz', price: '5.000₺' },
   { brand: 'Apple', model: 'Iphone SE', storage: '512GB', color: 'Siyah', price: '15.000₺' },
   { brand: 'Samsung', model: 'Galaxy A23', storage: '128GB', color: 'Beyaz', price: '15.000₺' },
   { brand: 'Apple', model: 'Iphone 12', storage: '128GB', color: 'Beyaz', price: '20.000₺' },
]